#!/bin/bash

SERVER_KEY="$HOME/.ssh/server.key"
SERVER_CRT="$HOME/.ssh/server.crt"

echo "~> openssl genrsa -out ${SERVER_KEY} 2048"
openssl genrsa -out ${SERVER_KEY} 2048

echo "~> openssl ecparam -genkey -name secp384r1 -out ${SERVER_KEY}"
openssl ecparam -genkey -name secp384r1 -out ${SERVER_KEY}

echo "~> openssl req -new -x509 -sha256 -key ${SERVER_KEY} -out ${SERVER_CRT} -days 3650"
openssl req -new -x509 -sha256 -key ${SERVER_KEY} -out ${SERVER_CRT} -days 3650