#!/bin/bash

NAME=${1:-server}

KEY_FILE="$HOME/.ssh/${NAME}.key"
CRT_FILE="$HOME/.ssh/${NAME}.crt"

echo "~> openssl genrsa -out ${KEY_FILE} 2048"
openssl genrsa -out ${KEY_FILE} 2048

echo "~> openssl ecparam -genkey -name secp384r1 -out ${KEY_FILE}"
openssl ecparam -genkey -name secp384r1 -out ${KEY_FILE}

echo "~> openssl req -new -x509 -sha256 -key ${KEY_FILE} -out ${CRT_FILE} -days 3650"
openssl req -new -x509 -sha256 -key ${KEY_FILE} -out ${CRT_FILE} -days 3650