#!/bin/bash

if [[ "${1}" == "amnezic" ]]; then
    BIN="amnezic-go/bin/amnezic-go"
elif  [[ "${1}" == "amnezic" ]]; then
    BIN="games-go/bin/games-go"
else
    print-error "unknown app! ( ${1} )"
    return
fi
shift

if [[ "${1}" == "prd" ]]; then
    GIT_DIR=${GIT_PRD_DIR}
elif  [[ "${1}" == "stg" ]]; then
    GIT_DIR=${GIT_STG_DIR}
else
    print-error "unknown env! ( ${1} )"
    return
fi

print-cmd "go-run ${GIT_STG_DIR}/${BIN} $*"
go-run ${GIT_STG_DIR}/${BIN} "$*"