#!/bin/bash

# global

CURRENT_DIR=$( dirname $0 )
SERVICE_DIR="${CURRENT_DIR}/services"

# option

DRY="0"
while [[ "${1}" =~ ^- ]]; do
    case "${1}" in
        -d|--dry)       DRY="1";;
        *)              print-error "unknown option ${1}"; exit 1;;
    esac
    shift
done

# exec

SERVICES=$( service-select $* )
for SERVICE in ${SERVICES}; do

    print-cmd "sudo cp ${SERVICE_DIR}/${SERVICE} /etc/systemd/system/${SERVICE}"
    if [[ "${DRY}" == "0" ]]; then
        sudo cp ${SERVICE_DIR}/${SERVICE} /etc/systemd/system/${SERVICE}
    fi

done

print-cmd "sudo systemctl daemon-reload"
if [[ "${DRY}" == "0" ]]; then
    sudo systemctl daemon-reload
fi

for SERVICE in ${SERVICES}; do

    print-cmd "sudo systemctl start ${SERVICE}"
    if [[ "${DRY}" == "0" ]]; then
        sudo systemctl start ${SERVICE}
    fi

    print-cmd "sudo systemctl enable ${SERVICE}"
    if [[ "${DRY}" == "0" ]]; then
        sudo systemctl enable ${SERVICE}
    fi

    print-cmd "sudo systemctl status ${SERVICE}"
    if [[ "${DRY}" == "0" ]]; then
        sudo systemctl status ${SERVICE}
    fi

done