#!/bin/bash

# global

CURRENT_DIR=$( dirname $0 )
SERVICE_DIR="${CURRENT_DIR}/services"

# option

SOURCE="default"
MODE="multi"
while [[ "${1}" =~ ^- ]]; do
    case "${1}" in
        --all)         SOURCE="all";;
        --available)   SOURCE="available";;
        --installed)   SOURCE="installed";;
        -m|--multi)    MODE="multi";;
        -s|--single)   MODE="single";;
        *)              print-error "unknown option ${1}"; exit 1;;
    esac
    shift
done

if [[ "${1}" =~ ^amnezic$ ]]; then
    PATTERN="amnezic.be.prd"
elif [[ "${1}" =~ ^games$ ]]; then
    PATTERN="games.be."
else
    PATTERN="${1}"
fi

if [[ "${SOURCE}" == "installed" ]]; then
    SERVICES=$( find /etc/systemd/system/ -name "*.srv" -printf "%f\n" )
elif [[ "${SOURCE}" == "all" ]]; then
    SITES=$( ( ls ${SERVICE_DIR} && find /etc/systemd/system/ -name "*.srv" -printf "%f\n" ) | sort | uniq )
else
    SERVICES=$( ls ${SERVICE_DIR} )
fi

if [[ "${MODE}" == "multi" ]]; then
    echo ${SERVICES} | split-lines | grep "${PATTERN}" | choose -m -h "Select services"
else
    echo ${SERVICES} | split-lines | grep "${PATTERN}" | choose -h "Select services"
fi