#!/bin/bash

# option

DRY="0"
while [[ "${1}" =~ ^- ]]; do
    case "${1}" in
        -d|--dry)       DRY="1";;
        *)              print-error "unknown option ${1}"; exit 1;;
    esac
    shift
done

# exec

for SERVICE in $( service-select $* ); do
    echo "~> sudo systemctl stop ${SERVICE}"
    if [[ "${DRY}" == "0" ]]; then
        sudo systemctl stop ${SERVICE}
    fi

    echo "~> sudo systemctl disable ${SERVICE}"
    if [[ "${DRY}" == "0" ]]; then
        sudo systemctl disable ${SERVICE}
    fi

    echo "~> sudo rm /etc/systemd/system/${SERVICE}"
    if [[ "${DRY}" == "0" ]]; then
        sudo rm /etc/systemd/system/${SERVICE}
    fi

done

echo "~> sudo systemctl daemon-reload"
if [[ "${DRY}" == "0" ]]; then
    sudo systemctl daemon-reload
fi

echo "~> sudo systemctl reset-failed"
if [[ "${DRY}" == "0" ]]; then
    sudo systemctl reset-failed
fi