#!/bin/bash

# option

DRY="0"
while [[ "${1}" =~ ^- ]]; do
    case "${1}" in
        -d|--dry)       DRY="1";;
        *)              print-error "unknown option ${1}"; exit 1;;
    esac
    shift
done

# exec

print-cmd "sudo systemctl daemon-reload"
if [[ "${DRY}" == "0" ]]; then
    sudo systemctl daemon-reload
fi

for SERVICE in $( service-select --installed $* ); do
    print-cmd "sudo systemctl stop ${SERVICE}"
    if [[ "${DRY}" == "0" ]]; then
        sudo systemctl stop ${SERVICE}
    fi

    print-cmd "sudo systemctl start ${SERVICE}"
    if [[ "${DRY}" == "0" ]]; then
        sudo systemctl start ${SERVICE}
    fi

    print-cmd "sudo journalctl -u ${SERVICE} -b --no-pager"
    if [[ "${DRY}" == "0" ]]; then
        sudo journalctl -u ${SERVICE} -b --no-pager
    fi
done