#!/bin/bash

# global

CURRENT_DIR=$( dirname $0 )
SERVICE_DIR="${CURRENT_DIR}/services"

# option

SOURCE="default"
MODE="multi"
while [[ "${1}" =~ ^- ]]; do
    case "${1}" in
        --all)         SOURCE="all";;
        --installed)   SOURCE="installed";;
        --uninstalled) SOURCE="uninstalled";;
        -m|--multi)    MODE="multi";;
        -s|--single)   MODE="single";;
        *)              print-error "unknown option ${1}"; exit 1;;
    esac
    shift
done

PATTERN="${1}"

INSTALLED_SERVICES=$( find /etc/systemd/system/ -maxdepth 1 -name "srv.*.service" -printf "%f\n" )
if [[ "${SOURCE}" == "installed" ]]; then
    SERVICES=${INSTALLED_SERVICES}
elif [[ "${SOURCE}" == "uninstalled" ]]; then
    # enforce installed to not be selected at the end
    SERVICES=$( ( ls ${SERVICE_DIR} && echo "${INSTALLED_SERVICES}" && echo "${INSTALLED_SERVICES}" ) | sort | uniq -u )
elif [[ "${SOURCE}" == "all" ]]; then
    SERVICES=$( ( ls ${SERVICE_DIR} && echo "${INSTALLED_SERVICES}" ) | sort | uniq )
else
    SERVICES=$( ls ${SERVICE_DIR} )
fi

if [[ "${SERVICES}" == "" ]]; then
    print-warning "no service"
    exit 1
fi

if [[ "${MODE}" == "multi" ]]; then
    echo ${SERVICES} | split-lines | grep "${PATTERN}" | choose -m -h "Select services"
else
    echo ${SERVICES} | split-lines | grep "${PATTERN}" | choose -h "Select services"
fi