#!/bin/bash

SERVICES="${1}"
if [[ "${SERVICES}" = "" ]]; then
    SERVICES=$( service-select --all $* )
fi

# exec

for SERVICE in $( echo "${SERVICES}" | split-lines ); do
    if [[ ! -e /etc/systemd/system/${SERVICE} ]]; then
        print-ko "${SERVICE} $( color orange "not installed" )"
    elif ( sudo systemctl is-enabled ${SERVICE} > /dev/null ); then
        if ( sudo systemctl is-active ${SERVICE} > /dev/null ); then
            print-ok "${SERVICE} $( color green active )"
        elif ( sudo systemctl is-failed ${SERVICE} > /dev/null ); then
            print-ko "${SERVICE} $( color red failed )"
            service-log "${SERVICE}"
        else 
            print-ko "${SERVICE} $( color gray unknown )"
        fi
    else
        print-ko "${SERVICE} $( color orange disabled )"
    fi
done