#!/bin/bash

# global

CURRENT_DIR=$( dirname $0 )
SITES_DIR="${CURRENT_DIR}/sites"

# option

MODE="multi"
while [[ "${1}" =~ ^- ]]; do
    case "${1}" in
        -a|--all)       MODE="multi-all";;
        -m|--multi)     MODE="multi";;
        -o|--one)       MODE="one";;
        -s|--single)    MODE="one";;
        *)              print-error "unknown option ${1}"; exit 1;;
    esac
    shift
done

PATTERN="${1}"

if [[ "${MODE}" == "multi-all" ]]; then
    ls ${SITES_DIR} | grep "${PATTERN}" | choose -a -h "Select sites"
elif [[ "${MODE}" == "multi" ]]; then
    ls ${SITES_DIR} | grep "${PATTERN}" | choose -m -h "Select sites"
else
    ls ${SITES_DIR} | grep "${PATTERN}" | choose -h "Select sites"
fi